networks:
  pocket:
    external: true

services:
  mysql:
    image: 'mysql:latest'
    container_name: 'illvent'
    environment:
      - 'MYSQL_DATABASE=illvent'
      - 'MYSQL_PASSWORD=1234'
      - 'MYSQL_ROOT_HOST='
      - 'MYSQL_ROOT_PASSWORD=1234'
      - 'MYSQL_USER=username'
    ports:
      - '3307:3306'
    restart: 'on-failure'
  redis:
    image: 'redis:latest'
    container_name: 'illvent_redis'
    ports:
      - '6379:6379'
